name: Release Package 🚀
on: workflow_dispatch
# push:
#   branches:
#     - com.nftport.nftport
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          dry_run: true
      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          branch: com.nftport.nftport
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          